export const SHIELDED_POOL_ABI = [
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "amount", type: "core::integer::u256" },
      { name: "commitment", type: "core::felt252" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "old_commitment", type: "core::felt252" },
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "old_amount", type: "core::felt252" },
      { name: "old_secret", type: "core::felt252" },
      { name: "old_nullifier_secret", type: "core::felt252" },
      { name: "new_commitment_sender", type: "core::felt252" },
      { name: "new_commitment_recipient", type: "core::felt252" },
      { name: "change_amount", type: "core::felt252" },
      { name: "transfer_amount", type: "core::felt252" },
      { name: "new_secret_sender", type: "core::felt252" },
      { name: "new_nullifier_secret_sender", type: "core::felt252" },
      { name: "new_secret_recipient", type: "core::felt252" },
      { name: "new_nullifier_secret_recipient", type: "core::felt252" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "prepare_withdraw",
    inputs: [
      { name: "commitment", type: "core::felt252" },
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "amount", type: "core::felt252" },
      { name: "secret", type: "core::felt252" },
      { name: "nullifier_secret", type: "core::felt252" },
      { name: "withdraw_amount", type: "core::integer::u256" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "claim_withdrawal",
    inputs: [
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "recipient", type: "core::starknet::contract_address::ContractAddress" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "is_commitment_valid",
    inputs: [{ name: "commitment", type: "core::felt252" }],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_nullifier_used",
    inputs: [{ name: "nullifier_hash", type: "core::felt252" }],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_commitment_count",
    inputs: [],
    outputs: [{ type: "core::integer::u64" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_total_deposited",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_btc_token",
    inputs: [],
    outputs: [{ type: "core::starknet::contract_address::ContractAddress" }],
    state_mutability: "view",
  },
] as const;
