export const SHIELDED_AMM_ABI = [
  {
    type: "function",
    name: "seed_liquidity",
    inputs: [
      { name: "btc_amount", type: "core::integer::u256" },
      { name: "strk_amount", type: "core::integer::u256" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "token_type", type: "core::felt252" },
      { name: "amount", type: "core::integer::u256" },
      { name: "commitment", type: "core::felt252" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "swap",
    inputs: [
      { name: "full_proof_with_hints", type: "core::array::Span::<core::felt252>" },
      { name: "root", type: "core::felt252" },
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "token_type_in", type: "core::felt252" },
      { name: "amount_in", type: "core::felt252" },
      { name: "token_type_out", type: "core::felt252" },
      { name: "new_commitment", type: "core::felt252" },
      { name: "amount_out", type: "core::felt252" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "prepare_withdraw",
    inputs: [
      { name: "full_proof_with_hints", type: "core::array::Span::<core::felt252>" },
      { name: "root", type: "core::felt252" },
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "token_type", type: "core::felt252" },
      { name: "withdraw_amount", type: "core::integer::u256" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "claim_withdrawal",
    inputs: [
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "recipient", type: "core::starknet::contract_address::ContractAddress" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_amount_out",
    inputs: [
      { name: "amount_in", type: "core::integer::u256" },
      { name: "token_type_in", type: "core::felt252" },
      { name: "token_type_out", type: "core::felt252" },
    ],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_btc_reserve",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_strk_reserve",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_nullifier_used",
    inputs: [{ name: "nullifier_hash", type: "core::felt252" }],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_commitment_count",
    inputs: [],
    outputs: [{ type: "core::integer::u64" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_seeded",
    inputs: [],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_btc_token",
    inputs: [],
    outputs: [{ type: "core::starknet::contract_address::ContractAddress" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_strk_token",
    inputs: [],
    outputs: [{ type: "core::starknet::contract_address::ContractAddress" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_last_root",
    inputs: [],
    outputs: [{ type: "core::felt252" }],
    state_mutability: "view",
  },
] as const;
