export const SHIELDED_POOL_ABI = [
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "token_address", type: "core::starknet::contract_address::ContractAddress" },
      { name: "amount", type: "core::integer::u256" },
      { name: "commitment", type: "core::felt252" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "full_proof_with_hints", type: "core::array::Span::<core::felt252>" },
      { name: "root", type: "core::felt252" },
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "new_commitment_sender", type: "core::felt252" },
      { name: "new_commitment_recipient", type: "core::felt252" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "prepare_withdraw",
    inputs: [
      { name: "full_proof_with_hints", type: "core::array::Span::<core::felt252>" },
      { name: "root", type: "core::felt252" },
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "token_address", type: "core::starknet::contract_address::ContractAddress" },
      { name: "withdraw_amount", type: "core::integer::u256" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "claim_withdrawal",
    inputs: [
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "recipient", type: "core::starknet::contract_address::ContractAddress" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "private_execute",
    inputs: [
      { name: "full_proof_with_hints", type: "core::array::Span::<core::felt252>" },
      { name: "root", type: "core::felt252" },
      { name: "nullifier_hash", type: "core::felt252" },
      { name: "token_address", type: "core::starknet::contract_address::ContractAddress" },
      { name: "amount", type: "core::integer::u256" },
      { name: "target_contract", type: "core::starknet::contract_address::ContractAddress" },
      { name: "call_data", type: "core::array::Span::<core::felt252>" },
      { name: "change_commitment", type: "core::felt252" },
      { name: "change_amount", type: "core::integer::u256" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "is_nullifier_used",
    inputs: [{ name: "nullifier_hash", type: "core::felt252" }],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_commitment_count",
    inputs: [],
    outputs: [{ type: "core::integer::u64" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_token_balance",
    inputs: [
      { name: "token_address", type: "core::starknet::contract_address::ContractAddress" },
    ],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_last_root",
    inputs: [],
    outputs: [{ type: "core::felt252" }],
    state_mutability: "view",
  },
] as const;
