export const ADDRESSES = {
  MOCK_BTC: process.env.NEXT_PUBLIC_MOCK_BTC!,
  MOCK_STRK: process.env.NEXT_PUBLIC_MOCK_STRK!,
  DEMO_TOKEN: process.env.NEXT_PUBLIC_DEMO_TOKEN!,
  DEMO_COUNTER: process.env.NEXT_PUBLIC_DEMO_COUNTER!,
  MOCK_PRAGMA_ORACLE: process.env.NEXT_PUBLIC_MOCK_PRAGMA_ORACLE!,
  PRIVATE_VOTING: process.env.NEXT_PUBLIC_PRIVATE_VOTING!,
  SHIELDED_POOL: process.env.NEXT_PUBLIC_SHIELDED_POOL!,
  SHIELDED_AMM: process.env.NEXT_PUBLIC_SHIELDED_AMM!,
  PREDICTION_MARKET: process.env.NEXT_PUBLIC_PREDICTION_MARKET!,
} as const;

export const TOKEN_TYPE_BTC = "1";
export const TOKEN_TYPE_STRK = "2";
